In [1]:
import numpy as np

In [2]:
W = np.array([0, 0, 0]) # World cordinate origin
C = np.array([50, 60, -20])  # Camera cordinate origin in world coordinate
Xw = np.array([200, 70, 50])  # 3D image point in world coordinate
Xw

array([200,  70,  50])

In [3]:
# Calculate Intrinsic Params

In [4]:
f = 10/0.05
px = 512
py = 512
K = np.array([f, 0, px, 0, f, py, 0, 0, 1]).reshape([3,3])
K

array([[200.,   0., 512.],
       [  0., 200., 512.],
       [  0.,   0.,   1.]])

In [5]:
# Calculate Extrinsic Params

In [7]:
R = np.array([[0.6124, -0.3536, 0.7071],[0.7392, 0.5732, 0.35356],[0.2803, 0.7392, 0.624]])
R

array([[ 0.6124 , -0.3536 ,  0.7071 ],
       [ 0.7392 ,  0.5732 ,  0.35356],
       [ 0.2803 ,  0.7392 ,  0.624  ]])

In [8]:
T = (W-C).reshape([-1, 1])
T

array([[-50],
       [-60],
       [ 20]])

In [9]:
t = -np.dot(R, T)
t

array([[-4.738 ],
       [64.2808],
       [45.887 ]])

In [10]:
Rt = np.concatenate((R, t), 1)
Rt

array([[ 0.6124 , -0.3536 ,  0.7071 , -4.738  ],
       [ 0.7392 ,  0.5732 ,  0.35356, 64.2808 ],
       [ 0.2803 ,  0.7392 ,  0.624  , 45.887  ]])

In [11]:
IT = np.concatenate((np.identity(3), -T), 1)
IT

array([[  1.,   0.,   0.,  50.],
       [  0.,   1.,   0.,  60.],
       [  0.,   0.,   1., -20.]])

In [12]:
# Calculate camera matrix

In [13]:
# Translate First
P = np.dot(K, R)
P = np.dot(P, IT)
P

array([[2.6599360e+02, 3.0775040e+02, 4.6090800e+02, 2.2546544e+04],
       [2.9135360e+02, 4.9311040e+02, 3.9020000e+02, 3.6350304e+04],
       [2.8030000e-01, 7.3920000e-01, 6.2400000e-01, 4.5887000e+01]])

In [14]:
# Rotate First
P = np.dot(K, Rt) 
P

array([[2.6599360e+02, 3.0775040e+02, 4.6090800e+02, 2.2546544e+04],
       [2.9135360e+02, 4.9311040e+02, 3.9020000e+02, 3.6350304e+04],
       [2.8030000e-01, 7.3920000e-01, 6.2400000e-01, 4.5887000e+01]])

In [16]:
# Convert world coordinate to image point

In [17]:
X = np.append(Xw, 1).reshape([-1, 1])

In [18]:
x = np.dot(P, X).flatten()
x

array([120333.192, 148648.752,    184.891])

In [20]:
Px = int(x[0]/x[2])
Py = int(x[1]/x[2])
print(f"Cartesian Image Point: x={Px}, y={Py}")

Cartesian Image Point: x=650, y=803
