In [131]:
import cv2
import numpy as np

In [132]:
Xw = np.array([200, 70, 50])
C = np.array([50, 60, -20])

In [110]:
t = (Xw - C).reshape([-1, 1])
t

array([[150],
       [ 10],
       [ 70]])

In [115]:
# t = -RC
R = -C/t
R

array([[-0.33333333, -0.4       ,  0.13333333],
       [-5.        , -6.        ,  2.        ],
       [-0.71428571, -0.85714286,  0.28571429]])

In [126]:
f = 10/0.05
px = 512
py = 512
K = np.array([f, 0, px, 0, f, py, 0, 0, 1]).reshape([3,3])
K

array([[200.,   0., 512.],
       [  0., 200., 512.],
       [  0.,   0.,   1.]])

In [129]:
P = np.dot(K, np.concatenate((R, t), 1))
P

array([[-4.32380952e+02, -5.18857143e+02,  1.72952381e+02,
         6.58400000e+04],
       [-1.36571429e+03, -1.63885714e+03,  5.46285714e+02,
         3.78400000e+04],
       [-7.14285714e-01, -8.57142857e-01,  2.85714286e-01,
         7.00000000e+01]])

In [151]:
X = np.append(Xw, 1).reshape([-1, 1])
x = np.dot(P, X).flatten()
x

array([-4.83085714e+04, -3.22708571e+05, -1.18571429e+02])

In [157]:
Px = x[0]/x[2]
Py = x[1]/x[2]
print(f"Image Point = x:{Px}, y:{Py}")

Image Point = x:407.4216867469881, y:2721.6385542168678
