In [129]:
import cv2
import numpy as np

In [130]:
W = np.array([0, 0, 0])
C = np.array([50, 60, -20])
Xw = np.append(np.array([200, 70, 50]),1).reshape([-1, 1])
Xw

array([[200],
       [ 70],
       [ 50],
       [  1]])

In [131]:
f = 10/0.05
px = 512
py = 512
K = np.array([f, 0, px, 0, f, py, 0, 0, 1]).reshape([3,3])
K

array([[200.,   0., 512.],
       [  0., 200., 512.],
       [  0.,   0.,   1.]])

In [120]:
# Calicaluete Extrinsic Params

In [121]:
t = (np.array([0, 0, 0]) - C).reshape([-1, 1])
t

array([[-50],
       [-60],
       [ 20]])

In [122]:
R = np.array([[0.6124, -0.3536, 0.7071],[0.7392, 0.5732, 0.35356],[0.2803, 0.7392, 0.624]])
R

array([[ 0.6124 , -0.3536 ,  0.7071 ],
       [ 0.7392 ,  0.5732 ,  0.35356],
       [ 0.2803 ,  0.7392 ,  0.624  ]])

In [123]:
Rt = np.concatenate((R, t), 1)
Rt

array([[  0.6124 ,  -0.3536 ,   0.7071 , -50.     ],
       [  0.7392 ,   0.5732 ,   0.35356, -60.     ],
       [  0.2803 ,   0.7392 ,   0.624  ,  20.     ]])

In [124]:
# Calculate camera matrix

In [125]:
P = np.dot(K, Rt)
P

array([[ 2.659936e+02,  3.077504e+02,  4.609080e+02,  2.400000e+02],
       [ 2.913536e+02,  4.931104e+02,  3.902000e+02, -1.760000e+03],
       [ 2.803000e-01,  7.392000e-01,  6.240000e-01,  2.000000e+01]])

In [126]:
# Convert world coordinate to image point

In [127]:
x = np.dot(P, X).flatten()
x

array([ 98026.648, 110538.448,    159.004])

In [128]:
Px = x[0]/x[2]
Py = x[1]/x[2]
print(f"Image Point = x:{Px}, y:{Py}")

Image Point = x:616.5042892002716, y:695.1928756509269
