In [288]:
import numpy as np

In [289]:
W = np.array([0, 0, 0]) # World cordinate origin
C = np.array([50, 60, -20])  # Camera cordinate origin in world coordinate
Xw = np.array([200, 70, 50])  # 3D image point in world coordinate
Xw

array([200,  70,  50])

In [290]:
# Calicaluete Intrinsic Params

In [291]:
f = 10/0.05
px = 512
py = 512
K = np.array([f, 0, px, 0, f, py, 0, 0, 1]).reshape([3,3])
K

array([[200.,   0., 512.],
       [  0., 200., 512.],
       [  0.,   0.,   1.]])

In [292]:
# Calicaluete Extrinsic Params

In [368]:
# Rotate first
R = np.array([[0.6124, -0.3536, 0.7071],[0.7392, 0.5732, 0.35356],[0.2803, 0.7392, 0.624]])
R

array([[ 0.6124 , -0.3536 ,  0.7071 ],
       [ 0.7392 ,  0.5732 ,  0.35356],
       [ 0.2803 ,  0.7392 ,  0.624  ]])

In [393]:
# Translate now
t = (W-C).reshape([-1, 1])
T = np.dot(R, t)
T

array([[  4.738 ],
       [-64.2808],
       [-45.887 ]])

In [394]:
RT = np.concatenate((R, Xc.reshape([-1, 1])), 1)
RT

array([[  0.6124 ,  -0.3536 ,   0.7071 ,   4.738  ],
       [  0.7392 ,   0.5732 ,   0.35356, -64.2808 ],
       [  0.2803 ,   0.7392 ,   0.624  , -45.887  ]])

In [354]:
# Calculate camera matrix

In [389]:
P = np.dot(K, RT)
P

array([[ 2.6599360e+02,  3.0775040e+02,  4.6090800e+02, -2.2546544e+04],
       [ 2.9135360e+02,  4.9311040e+02,  3.9020000e+02, -3.6350304e+04],
       [ 2.8030000e-01,  7.3920000e-01,  6.2400000e-01, -4.5887000e+01]])

In [356]:
# Convert world coordinate to image point

In [390]:
X = np.append(Xw,1).reshape([-1, 1])

In [391]:
x = np.dot(P, X).flatten()
x

array([75240.104, 75948.144,    93.117])

In [392]:
Px = int(x[0]/x[2])
Py = int(x[1]/x[2])
print(f"Cartesian Image Point: x={Px}, y={Py}")

Cartesian Image Point: x=808, y=815
